name: bqplot-test
channels:
    - conda-forge
dependencies:
    - pip
    - python
    - yarn <2
    - nodejs=16
    - ipywidgets >=8
    - traitlets >=4.3.0
    - traittypes >=0.0.6
    - numpy >=1.10.4,<2.0.0
    - pandas >=1.0.0,<2.0.0
    - scipy
    - jupyterlab=3.2
    # Using Notebook 6 in CI st. we can test the old nbextension
    - notebook =6
    - jupyter-packaging
    - pytest <8
    - nbval
    - pytest-cov
    - selenium
    - flake8
    - nose
    - codespell
